name: mne_bids
channels:
- conda-forge
dependencies:
- python<3.11
- pip
- pip:
  - mne_bids
  - mne>=1.0
  - numpy>=1.16.0
  - scipy>=1.2.0
  - setuptools
  - nibabel>=2.5.0
  - pybv>=0.7.3
  - matplotlib>=3.1.0
  - pandas>=0.24.0
  - EDFlib-Python>=1.0.6
  - pymatreader>=0.0.29
  - nilearn
  - openneuro-py>=2022.1
  - mne-nirs
  - seaborn
  - scikit-learn>=0.21.0
